### PR TITLE
Soft teacher reliable metrics

### PR DESCRIPTION
**Pull request by danish87**
The issue with the dist training has been resolved by removing torchmetric inheritance for kitti_eval_class https://github.com/danish87/OpenPCDet/blob/3b10c03460bf750745e5a875856b918168ee1a11/pcdet/utils/stats_utils.py#L24 while other stats can be accumulated over different GPUs https://github.com/danish87/OpenPCDet/blob/3b10c03460bf750745e5a875856b918168ee1a11/pcdet/utils/stats_utils.py#L66.
For other stats pred_ious, pred_accs,pred_fgs,sem_score_fgs,sem_score_bgs,num_pred_boxes,num_gt_boxes torchmetric functionality over distributed GPUs seems to be working. 
Config has been updated to handle different metric testing without the need to comment the code https://github.com/danish87/OpenPCDet/blob/3b10c03460bf750745e5a875856b918168ee1a11/tools/cfgs/kitti_models/pv_rcnn_ssl_60.yaml#L225

### CODE REVIEW

**Comment by fnozarian** [comment]
Thanks for the PR.
I wonder how  KittiEvalMetric would work in the distributed mode without Torchmetrics because [its states](https://github.com/danish87/OpenPCDet/blob/3b10c03460bf750745e5a875856b918168ee1a11/pcdet/utils/stats_utils.py#L46-L48) are not synced across GPUs.

**Comment by danish87** [comment]
You are right for that reason, the compute call for mean-metric should have already synched all stats accross different GPUs

https://github.com/danish87/OpenPCDet/blob/3b10c03460bf750745e5a875856b918168ee1a11/pcdet/utils/stats_utils.py#L180

**Comment by fnozarian** [comment]
@danish87 Yes `MeanMetrics` should work fine, but not `KittiEvalMetric`, because [MeanMetrics states](https://github.com/danish87/OpenPCDet/blob/3b10c03460bf750745e5a875856b918168ee1a11/pcdet/utils/stats_utils.py#L70-L76) are different from the [KittiEvalMetric states](https://github.com/danish87/OpenPCDet/blob/3b10c03460bf750745e5a875856b918168ee1a11/pcdet/utils/stats_utils.py#L46-L48). We should also sync KittiEvalMetric states across GPUs.

**Comment by danish87** [comment]
@fnozarian yes you are right.

**Pull request closed without merging**
